// <auto-generated />
namespace WebApi.RegisterInformation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class intial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial2));
        
        string IMigrationMetadata.Id
        {
            get { return "202003291207559_intial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
